server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:dev2023
    username: dev2023
    password: dev2023
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update # Mude de create para update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false